# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'AzureFreesubscription(3c5d8c9c-8551-4f43-b202-847f7cc85f74)'
    subscriptionId: '3c5d8c9c-8551-4f43-b202-847f7cc85f74'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'azpipelinetest'
    location: 'East US'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://github.com/DrealDidihttps://github.com/DrealDidi/aztest/blob/main/deploytest/aztest/blhttps://github.com/DrealDidi/aztest/blob/main/deploylinkedob/main/deploytest'
    deploymentMode: 'Incremental'
    deploymentName: 'aztestpiepline'